import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Provider } from "react-redux";
import Store from "./store/Store";
import MyApp from "@/components/Myapp";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyApp>
      <html lang="en">
        <body className={inter.className}>
          <div className="wrapper">
            <Sidebar />
            <div className="right-side">
              <Header />
              <div className="">{children}</div>
            </div>
          </div>
        </body>
      </html>
    </MyApp>
  );
}
